// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Montadora_Arlisson_Menacho.Contexto;

namespace Montadora_Arlisson_Menacho.Migrations
{
    [DbContext(typeof(MontadoraContexto))]
    partial class MontadoraContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Cidade", b =>
                {
                    b.Property<int>("Cidadeid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Cidadeid");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Peca", b =>
                {
                    b.Property<int>("PecaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("DtFabricacao");

                    b.Property<string>("NumeroSerie");

                    b.Property<int?>("ObjFornecedorId");

                    b.Property<decimal>("Valor");

                    b.HasKey("PecaId");

                    b.HasIndex("ObjFornecedorId");

                    b.ToTable("Pecas");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.PecaDoVeiculo", b =>
                {
                    b.Property<int>("PecadoVeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Desconto");

                    b.Property<int?>("ObjPecaPecaId");

                    b.Property<int>("Quantidade");

                    b.Property<int?>("Veiculoid");

                    b.HasKey("PecadoVeiculoId");

                    b.HasIndex("ObjPecaPecaId");

                    b.HasIndex("Veiculoid");

                    b.ToTable("PecaDosVeiculos");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pessoa");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Usuario", b =>
                {
                    b.Property<int>("Usuarioid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("Usuarioid");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Veiculo", b =>
                {
                    b.Property<int>("Veiculoid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.Property<int?>("ObjClienteId");

                    b.Property<int?>("ObjMontadorId");

                    b.Property<int?>("ObjUsuarioUsuarioid");

                    b.HasKey("Veiculoid");

                    b.HasIndex("ObjClienteId");

                    b.HasIndex("ObjMontadorId");

                    b.HasIndex("ObjUsuarioUsuarioid");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Cliente", b =>
                {
                    b.HasBaseType("Montadora_Arlisson_Menacho.Models.Pessoa");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Endereco");

                    b.Property<string>("Numero");

                    b.Property<int?>("ObjCidadeCidadeid");

                    b.Property<string>("Orgaoexpedidor");

                    b.Property<string>("Rg");

                    b.HasIndex("ObjCidadeCidadeid");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Fornecedor", b =>
                {
                    b.HasBaseType("Montadora_Arlisson_Menacho.Models.Pessoa");

                    b.Property<string>("Endereco")
                        .HasColumnName("Fornecedor_Endereco");

                    b.HasDiscriminator().HasValue("Fornecedor");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Montador", b =>
                {
                    b.HasBaseType("Montadora_Arlisson_Menacho.Models.Pessoa");

                    b.Property<decimal>("Salario");

                    b.HasDiscriminator().HasValue("Montador");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Peca", b =>
                {
                    b.HasOne("Montadora_Arlisson_Menacho.Models.Fornecedor", "ObjFornecedor")
                        .WithMany()
                        .HasForeignKey("ObjFornecedorId");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.PecaDoVeiculo", b =>
                {
                    b.HasOne("Montadora_Arlisson_Menacho.Models.Peca", "ObjPeca")
                        .WithMany()
                        .HasForeignKey("ObjPecaPecaId");

                    b.HasOne("Montadora_Arlisson_Menacho.Models.Veiculo")
                        .WithMany("ListapecaDoVeiculos")
                        .HasForeignKey("Veiculoid");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Veiculo", b =>
                {
                    b.HasOne("Montadora_Arlisson_Menacho.Models.Cliente", "ObjCliente")
                        .WithMany()
                        .HasForeignKey("ObjClienteId");

                    b.HasOne("Montadora_Arlisson_Menacho.Models.Montador", "ObjMontador")
                        .WithMany()
                        .HasForeignKey("ObjMontadorId");

                    b.HasOne("Montadora_Arlisson_Menacho.Models.Usuario", "ObjUsuario")
                        .WithMany()
                        .HasForeignKey("ObjUsuarioUsuarioid");
                });

            modelBuilder.Entity("Montadora_Arlisson_Menacho.Models.Cliente", b =>
                {
                    b.HasOne("Montadora_Arlisson_Menacho.Models.Cidade", "ObjCidade")
                        .WithMany()
                        .HasForeignKey("ObjCidadeCidadeid");
                });
#pragma warning restore 612, 618
        }
    }
}
